SHASPLabs2-4/Controllers/CatalogController.cs
using LinqKit;
using SHASPLabs2_4.Models;
using SHASPLabs2_4.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SHASPLabs2_4.Controllers
{
    public class CatalogController : Controller
    {
        JuiceContext db = new JuiceContext();

        public ActionResult Catalog(string searchString, string sort)
        {
            List<Juice> juices = db.Juices.ToList();

            if (!string.IsNullOrEmpty(searchString))
            {
                juices = Search(searchString);
            }

            if (!string.IsNullOrEmpty(sort))
            {
                if (sort == "Имя")
                {
                    juices = db.Juices.OrderBy(a => a.Name).ToList();
                }
                else if (sort == "Производитель")
                {
                    juices = db.Juices.OrderBy(a => a.Maker).ToList();
                }
                else if (sort == "Цена")
                {
                    juices = db.Juices.OrderBy(a => a.Price).ToList();
                }
            }

            return View(juices);
        }

        [HttpGet]
        public ActionResult Buy(int? id)
        {
            ViewBag.JuiceId = id;
            return View();
        }

        [HttpPost]
        public ActionResult Buy(Purchase purchase)
        {
            purchase.Date = DateTime.Now;
            Cart.Cart cart = (Cart.Cart)Session["Cart" + User.Identity.Name];
            if (cart != null && cart.Lines.Count() > 0)
            {
                foreach (var item in cart.Lines)
                {
                    purchase.JuiceId = item.Juice.Id;
                    for (int i = 0; i < item.Quantity; i++)
                    {
                        db.Purchases.Add(purchase);
                        db.SaveChanges();
                    }
                }
                PurchCartViewModel purchCartViewModel = new PurchCartViewModel { Purchase = purchase, Count = cart.Lines.Count() };
                cart.Clear();
                return View("BoughtAll", purchCartViewModel);
            }
            else
            {
                db.Purchases.Add(purchase);
            }
            db.SaveChanges();
            return RedirectToAction("Bought", purchase);
        }

        [HttpGet]
        public ActionResult Bought(Purchase purchase)
        {
            return View(purchase);
        }

        private List<Juice> Search(string searchString)
        {
            var predicate = PredicateBuilder.New<Juice>(e => false);


            Category category = db.Categories.FirstOrDefault(a => a.Name == searchString);

            if (category != null)
            {
                predicate.Or(a => a.CategoryId == category.Id);
            }
            //predicate.Or(a => a.Name == searchString);
            //predicate.Or(a => a.Maker == searchString);
            predicate.Or(a => a.Name.StartsWith(searchString));
            predicate.Or(a => a.Maker.StartsWith(searchString));
            if (Int32.TryParse(searchString, out int result1))
            {
                predicate.Or(a => a.Price == result1);
            }
            if (DateTime.TryParse(searchString, out DateTime result2))
            {
                predicate.Or(a => a.ShelfLife == result2);
            }

            return new List<Juice>(db.Juices.Where(predicate));

        }
    }
}

SHASPLabs2-4/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Магазин вафлей", "Main", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                @if (User.Identity.IsAuthenticated)
                {
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Каталог", "Catalog", "Catalog")</li>
                    </ul>
                    <div class="nav navbar-nav dropdown">
                        <p class="dropbtn">Редактирование</p>
                        <div class="dropdown-content">
                            @Html.ActionLink("Сок", "Edit", "Edit")
                            @Html.ActionLink("Категория", "Category", "Category")
                            @Html.ActionLink("Поставщик", "Supplier", "Supplier")
                            @Html.ActionLink("Поставка", "Delivery", "Delivery")
                            @Html.ActionLink("Покупка", "Purchase", "Purchase")
                        </div>
                    </div>

                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Корзина", "Cart", "Cart")</li>
                    </ul>
                }
                @Html.Partial("_LoginPartial")
            </div>

        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>